spring:
  rabbitmq:
    host: 49.235.100.175
    port: 5672
    username: admin
    password: admin
    publisher-confirm-type: correlated
    publisher-returns: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
